[package]
name = "text-script-exp"
version = "0.0.0"
authors = ["mig4 <42650719@auril.club>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
